#!/bin/bash
cd wfcroot
git submodule foreach eval "git commit -am '$1' || true"
cd ..
git submodule foreach eval "git commit -am '$1' || true"
git submodule foreach --recursive git push
git commit -am '$1' 
git push

